### ISSUE TITLE
Why can't the name resolver support traditional DNS Records?

### ISSUE THREAD

**Issue by decartesol** [Bonfida/name-resolver#5]
Users of SNS (like myself) want more customizability than the `url` record that Bonfida allows to be set.
I want to be able to set records the rest of the internet uses like `A`, `CNAME`, `MX`, etc.

**Comment by decartesol** [comment]
I'm interested in contributing to the SNS IP repo. Mainly my use-case is I want someone to be able to navigate to my .sol address and then rather than a redirect happening in the URL bar, they would see my site loaded while the FQDN remains my .sol address. Basically the same thing that happens with any normal website. Hence why I'm asking for A and CNAME records.

**Comment by dr497** [comment]
We released the SNS-IP repo https://github.com/Bonfida/sns-ip 

We would love to have your feedback on SNS-IP1 https://github.com/Bonfida/sns-ip/issues/3

**Comment by decartesol** [comment]
@dr497 should we re-open this to implement the A & CNAME records support given that [SNS-IP1](https://github.com/Bonfida/sns-ip/issues/3) marked as completed?

I'd be willing to take on that work. 

I'm hoping Bonfida could pay me a small amount for that work. For example 10 to 50 SOL depending on how complex it is.
I'm an anon dev that needs funds in order to deploy programs.

**Comment by dr497** [comment]
Hi @decartesol ! I have added support CNAME and A record support on this PR https://github.com/Bonfida/name-resolver/pull/7/files

**Comment by dr497** [comment]
@GeoBrodas The PR for CNAME support was never merged so it won't support `CNAME` record but it will support `URL`, `IPFS`, `ARWV` and `SHDW` records. 

We are planning to refactor this cloudflare worker from Rust to Typescript and add `CNAME` support in the coming weeks.

**Comment by GeoBrodas** [comment]
Alrightyy 👍🏼

**Comment by dr497** [comment]
@GeoBrodas `CNAME` should now be supported

**Comment by GeoBrodas** [comment]
@dr497 So now setting it here should work fine?
![image](https://github.com/Bonfida/name-resolver/assets/68821192/5032fb11-f0eb-4820-af61-b432dabe1839)

**Comment by ahu** [comment]
> Hi [@decartesol](https://github.com/decartesol) ! I have added support CNAME and A record support on this PR https://github.com/Bonfida/name-resolver/pull/7/files

I’m a beginner — I just bought a .sol domain and set up both IPNS and an A record. However, when I visit my .sol domain in the Brave browser, it doesn’t open the website corresponding to the A record (net::ERR_NAME_NOT_RESOLVED). Could you please advise me on what I should do? Thank you!
